### ISSUE TITLE
BFS question

### ISSUE THREAD

**Issue by jinz2014** [dbaranchuk/learning-to-route#1]
Hi

It is interesting to browse your paper and code.  I am not sure if BFS may be accelerated using a GPU. The current implementation uses OpenMP.

Thanks

**Comment by dbaranchuk** [comment]
Hi,

Thanks for your proposal. Indeed, it sounds reasonable to use CUDA bfs implementation. I did not think about it at the submission time. At first sight, it seems not so difficult to implement by using [pycuda](https://github.com/inducer/pycuda). If there are many interested people, I'll consider to carry out it sometime. Also, if you implement it as a part of your project, I would be happy to look at this.
