### ISSUE TITLE
Missing DATA directory 

### ISSUE THREAD

**Issue by udaymallappa** [dbaranchuk/learning-to-route#2]
I do not see DATA directory (that was used in your notebooks). Is it possible to upload it.

**Comment by justheuristic** [comment]
I'm not 100% sure, but when i tried to reproduce the paper, all notebooks simply *created* the data directory and downloaded the... well... data into it.

For instance, [this notebook](https://github.com/dbaranchuk/learning-to-route/blob/online/notebooks/DEEP100K_dcs128_gcn_size96_routing120_verification8.ipynb) does it with these lines:

```
DATA_DIR = './data/DEEP100K'

if not os.path.exists(DATA_DIR):
    assert not DATA_DIR.endswith(os.sep), 'please do not put "/" at the end of DATA_DIR'
    !mkdir -p {DATA_DIR}
    !wget https://www.dropbox.com/sh/oc8tswkzrdqe4vi/AADSOL74QIBtg_EvOdBYOX3na?dl=1 -O {DATA_DIR}/deep_100k.zip
    !cd {DATA_DIR} && unzip deep_100k.zip
```

**Comment by justheuristic** [comment]
I'm not 100% sure, but when i tried to reproduce the paper, all notebooks simply *created* the data directory and downloaded the... well... data into it.

For instance, [this notebook](https://github.com/dbaranchuk/learning-to-route/blob/online/notebooks/DEEP100K_dcs128_gcn_size96_routing120_verification8.ipynb) does it with these lines:

```
DATA_DIR = './data/DEEP100K'

if not os.path.exists(DATA_DIR):
    assert not DATA_DIR.endswith(os.sep), 'please do not put "/" at the end of DATA_DIR'
    !mkdir -p {DATA_DIR}
    !wget https://www.dropbox.com/sh/oc8tswkzrdqe4vi/AADSOL74QIBtg_EvOdBYOX3na?dl=1 -O {DATA_DIR}/deep_100k.zip
    !cd {DATA_DIR} && unzip deep_100k.zip
```
